---
# tasks file for reboot
# 재부팅 작업
- name: Reboot a host
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action: wait_for host={{ inventory_hostname }}
                port=22 state=started delay=10
  become: false
                             
